# Generated by Django 3.2.5 on 2021-07-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_rename_autos_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Nickname',
            new_name='nickname',
        ),
    ]
