# Generated by Django 3.2.5 on 2021-07-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_rename_nickname_auto_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='Mileage',
            new_name='mileage',
        ),
    ]
