# Generated by Django 3.2.5 on 2021-07-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_rename_nickname_cat_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Foods',
            new_name='foods',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Weight',
            new_name='weight',
        ),
    ]
