# Generated by Django 3.2.5 on 2021-08-14 19:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'please write comment longer than 3 charachters ')])),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics.pic')),
            ],
        ),
        migrations.AddField(
            model_name='pic',
            name='comments',
            field=models.ManyToManyField(related_name='pic_comments', through='pics.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
