# Generated by Django 3.2.5 on 2021-07-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/images.png', upload_to='media'),
        ),
    ]
