# Generated by Django 3.2.5 on 2021-07-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images.png', upload_to=''),
        ),
    ]
